### ISSUE TITLE
Bug: Error when importing podcast cover

### ISSUE THREAD

**Issue by eteubert** [podlove/publisher-services#52]
Maybe unable to handle the Umlaut?

```
[error] podcast_copy_image reason: %Mint.HTTPError{reason: {:invalid_header_value, "content-disposition", "attachment; filename=\"Bücher-sind-wie-Kekse-cover.png\""}, module: Mint.HTTP1}
```

**Comment by dnkbln** [comment]
Ich habe den Fehler auf der Client-Seite behoben. Der übergebene Name wird jetzt vor der Übergabe geprüft und ggf. gesäubert. Damit tritt der Fehler nicht mehr auf. Siehe #55
